[package]
name = "vultus-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
nutype = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
